version: '3'

# These are the PRODUCTION defaults for docker-compose.yml
# It is intended to be run in production mode via Docker stack, not docker-compose.
# There are development overrides specified in docker-compose.override.yml, which are intended to be run in docker-compose.
# In addition, your system should have three files for environmental variables, none of which should be committed to git:
#  .env
#  .env.produciton
#  .env.development

services:
  db:
    image: cottagelabs/willow-db
    build: db/
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 250M

  solr:
    image: cottagelabs/willow-solr
    build: solr/
    volumes:
      - solr_home:/solr_home
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 250M
  
  redis:
    image: cottagelabs/willow-redis
    build: redis/
    volumes:
      - redis_data:/data
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 250M

  fedora:
    image: cottagelabs/willow-fedora
    build: fedora_commons/
    env_file: .env
    links:
      - db
    volumes:
       - fcrepo4_home:/fcrepo4_home/
       - fcrepo4_data:/fcrepo4_data/
    depends_on:
      - db
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 500M
  
  willow:
    image: cottagelabs/willow
    build:
      context: willow/
      args:
        - RAILS_ENV=production
    env_file:
      - .env
      - .env.production
    ports:
      - "${WILLOW_EXPOSED_PORT:-3000}:3000"
    links:
      - redis
      - solr
      - db
      - fedora
    depends_on:
      - fedora
      - db
      - solr
      - redis
    volumes:
      - derivatives:/derivatives
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 500M


  geoblacklight:
    image: cottagelabs/willow-geoblacklight
    build:
      context: geoblacklight/
      args:
        - RAILS_ENV=production
    env_file:
      - .env
      - .env.production
    ports:
      - "${GEOBLACKLIGHT_EXPOSED_PORT:-3010}:3010"
    links:
      - solr
      - db
    restart: on-failure
    deploy:
      resources:
        reservations:
          memory: 250M


volumes:
  redis_data: {}
  fcrepo4_home: {}
  fcrepo4_data: {}
  postgres_data: {}
  solr_home: {}
  derivatives: {}
