default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: willow_development

test:
  <<: *default
  database: willow_test

production:
  <<: *default
  database: willow_production
