development:
  host: <%= ENV['REDIS_HOST'] || 'redis' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
test:
  host: <%= ENV['REDIS_HOST'] || 'redis' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
production:
  host: <%= ENV['REDIS_HOST'] || 'redis' %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
